name: Deploy Spring Boot Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'Back/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x ./Back/ot/gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Back/ot

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ./Back/ot/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./Back/ot/build/libs

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: List files
        run: ls -R
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ot'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Back/ot/build/libs/ill-0.0.1-SNAPSHOT.jar
